spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: flowlinker-events
  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      adjust-dates-to-context-time-zone: false
  data:
    mongodb:
      uri: ${MONGODB_URI}
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    virtual-host: ${RABBITMQ_VHOST:/}

server:
  port: ${SERVER_PORT:9090}

app:
  rabbit:
    queue:
      activity: ${RABBIT_QUEUE_ACTIVITY:events.activity}
      campaign: ${RABBIT_QUEUE_CAMPAIGN:events.campaign}
      security: ${RABBIT_QUEUE_SECURITY:events.security}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized

logging:
  level:
    root: INFO
    org.springframework.amqp: INFO
    org.springframework.data.mongodb: INFO
    com.flowlinker.events: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG

